var jQuery = {};

jQuery.fn = jQuery.prototype;
jQuery.fx = {};
jQuery.fx.interval;
jQuery.guid;
jQuery.inArray = function ( array, callback ) {};
jQuery.isEmptyObject = function ( object ) {};
jQuery.isFunction = function ( obj ) {};
jQuery.makeArray = function ( obj ) {};
jQuery.noop = function() {};
jQuery.support = {};
jQuery.support.changeBubbles;

jQuery.fn.addClass = function ( className ) {};
jQuery.fn.append = function ( content ) {};
jQuery.fn.appendTo = function ( target ) {};
jQuery.fn.attr = function ( attributeName, value ) {};
jQuery.fn.bind = function ( eventType, handler ) {};
jQuery.fn.children = function() {};
jQuery.fn.contents = function() {};
jQuery.fn.css = function ( propertyName, value ) {};
jQuery.fn.detach = function() {};
jQuery.fn.each = function ( callback ) {};
jQuery.fn.eq = function ( index ) {};
jQuery.fn.fadeIn = function() {};
jQuery.fn.fadeOut = function() {};
jQuery.fn.height = function() {};
jQuery.fn.hide = function() {};
jQuery.fn.innerHeight = function() {};
jQuery.fn.innerWidth = function() {};
jQuery.fn.is = function ( selector ) {};
jQuery.fn.map = function ( array, callback ) {};
jQuery.fn.offset = function ( coordinates ) {};
jQuery.fn.offsetParent = function() {};
jQuery.fn.outerHeight = function() {};
jQuery.fn.outerWidth = function() {};
jQuery.fn.parent = function() {};
jQuery.fn.removeAttr = function ( attributeName ) {};
jQuery.fn.removeClass = function ( className ) {};
jQuery.fn.scroll = function() {};
jQuery.fn.scrollTop = function ( value ) {};
jQuery.fn.unbind = function ( eventType ) {};
jQuery.fn.width = function() {};
jQuery.fn.wrapAll = function ( wrappingElement ) {};